python my_reader.py \
    --batch_size 1 \
    --test_data ./data/test.tsv \
    --word_dict_path ./conf/word.dic \
    --label_dict_path ./conf/tag.dic \
    --word_rep_dict_path ./conf/q2b.dic \
    --save_bin_path ./data/test_eval_1000.bin \
    --word_emb_dim 128 \
    --grnn_hidden_dim 128 \
    --bigru_num 2 \
